[[redirects]]
  from = "/Home"
  to = "/"
  status = 301

[[redirects]]
  from = "/Brands"
  to = "/brands"
  status = 301

[[redirects]]
  from = "/Merchandise"
  to = "/merchandise"
  status = 301

[[redirects]]
  from = "/About"
  to = "/about"
  status = 301

[[redirects]]
  from = "/Career"
  to = "/career"
  status = 301

[[redirects]]
  from = "/Contact"
  to = "/contact"
  status = 301

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
